name: Update Timetable Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-timetable:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    
    - name: Create Google Auth credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
    
    - name: Update timetable data
      env:
        SPREADSHEET_ID: ${{ vars.SPREADSHEET_ID }}
        SHEET_NAME: ${{ vars.SHEET_NAME }}
      run: |
        python scripts/update_timetable.py
    
    - name: Cleanup credentials
      if: always()
      run: |
          rm -f credentials.json

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Timetable.csv Updated_Processed_Timetable.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update timetable data [skip ci]" && git push) 